from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import sys

from core.capability_model import CommandRequest, EffectClass
from core.effects import ExecutionSession
from core.config import (
    DEFAULT_QUERY_ORCHESTRATOR_ENABLED,
    DEFAULT_QUERY_ORCHESTRATOR_MAX_FILES,
    DEFAULT_QUERY_ORCHESTRATOR_MAX_ITERATIONS,
    DEFAULT_QUERY_ORCHESTRATOR_MAX_TOKENS,
    DEFAULT_QUERY_ORCHESTRATOR_MAX_WALL_TIME_MS,
    DEFAULT_QUERY_PLANNER_ENABLED,
    DEFAULT_QUERY_PLANNER_MAX_CODE_VARIANTS,
    DEFAULT_QUERY_PLANNER_MAX_LATENCY_MS,
    DEFAULT_QUERY_PLANNER_MAX_TERMS,
)
from core.init_foundation import (
    INIT_OUTPUT_LANGUAGE_CHOICES,
    INIT_REVIEW_STRICTNESS_CHOICES,
    INIT_SOURCE_SCOPE_CHOICES,
    INIT_SOURCE_SCOPE_DEFAULT,
    INIT_TEMPLATES,
    INIT_TEMPLATE_CHOICES,
    InitTemplate,
)
from core.output_contracts import build_contract, emit_contract_json
from core.repo_io import write_forge_file

MANAGED_REPO_FILES = (
    "config.toml",
    "review-rules.toml",
    "template-meta.toml",
)
MANAGED_LOCAL_FILES = ("config.local.toml.example",)


def _prompt_choice(label: str, options: list[str], default: str) -> str:
    while True:
        print(f"{label} [{'/'.join(options)}] (default: {default})")
        raw = input("> ").strip().lower()
        if not raw:
            return default
        if raw in options:
            return raw
        print(f"Invalid choice '{raw}'.")


def _prompt_yes_no(label: str, default: bool) -> bool:
    default_hint = "Y/n" if default else "y/N"
    while True:
        print(f"{label} [{default_hint}]")
        raw = input("> ").strip().lower()
        if not raw:
            return default
        if raw in {"y", "yes"}:
            return True
        if raw in {"n", "no"}:
            return False
        print(f"Invalid choice '{raw}'.")


def _parse_framework_allowlist(raw: str | None) -> list[str]:
    if not raw:
        return []
    out: list[str] = []
    seen: set[str] = set()
    for part in raw.split(","):
        value = part.strip()
        if not value:
            continue
        key = value.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(value)
    return out


def _render_framework_allowlist(values: list[str]) -> str:
    if not values:
        return "[]"
    quoted = ", ".join(f'"{item}"' for item in values)
    return f"[{quoted}]"


def _render_config(
    template: InitTemplate,
    output_language: str,
    index_enrichment_enabled: bool,
    source_scope_default: str,
    framework_allowlist: list[str],
) -> str:
    enrichment = "true" if index_enrichment_enabled else "false"
    planner_enabled = "true" if DEFAULT_QUERY_PLANNER_ENABLED else "false"
    orchestrator_enabled = "true" if DEFAULT_QUERY_ORCHESTRATOR_ENABLED else "false"
    return f"""# Generated by `forge init`
# Repository-owned Forge defaults. Commit this file.

[llm]
# Provider is intentionally unset in repo baseline.
# Configure provider/base_url/model in .forge/config.local.toml.

[llm.query_planner]
enabled = {planner_enabled}
mode = "{template.planner_mode}"
max_terms = {DEFAULT_QUERY_PLANNER_MAX_TERMS}
max_code_variants = {DEFAULT_QUERY_PLANNER_MAX_CODE_VARIANTS}
max_latency_ms = {DEFAULT_QUERY_PLANNER_MAX_LATENCY_MS}

[llm.query_orchestrator]
enabled = {orchestrator_enabled}
mode = "{template.orchestrator_mode}"
max_iterations = {DEFAULT_QUERY_ORCHESTRATOR_MAX_ITERATIONS}
max_files = {DEFAULT_QUERY_ORCHESTRATOR_MAX_FILES}
max_tokens = {DEFAULT_QUERY_ORCHESTRATOR_MAX_TOKENS}
max_wall_time_ms = {DEFAULT_QUERY_ORCHESTRATOR_MAX_WALL_TIME_MS}

[llm.prompt]
output_language = "{output_language}"

[query.source_policy]
source_scope_default = "{source_scope_default}"
framework_allowlist = {_render_framework_allowlist(framework_allowlist)}

[index.enrichment]
enabled = {enrichment}
summary_version = 1
max_summary_chars = 220
"""


def _render_review_rules(review_strictness: str) -> str:
    severity = "high" if review_strictness == "strict" else "medium"
    recommendation = "Resolve or explicitly justify TODO/FIXME markers in reviewed scope."
    return f"""# Generated by `forge init`
# Repository-owned review baseline rules. Commit this file.

[[rule]]
id = "todo_fixme_baseline"
title = "TODO/FIXME markers in review scope"
severity = "{severity}"
pattern = "(TODO|FIXME)"
explanation = "TODO/FIXME markers can indicate unfinished behavior or known risk."
recommendation = "{recommendation}"
"""


def _render_template_meta(
    *,
    template_id: str,
    interactive: bool,
    review_strictness: str,
    output_language: str,
    index_enrichment_enabled: bool,
    source_scope_default: str,
    framework_allowlist: list[str],
) -> str:
    now = datetime.now(timezone.utc).isoformat()
    enrichment = "true" if index_enrichment_enabled else "false"
    mode = "interactive" if interactive else "non_interactive"
    return f"""# Generated by `forge init`

template_id = "{template_id}"
template_version = 1
initialized_at = "{now}"
init_mode = "{mode}"
review_strictness = "{review_strictness}"
output_language = "{output_language}"
index_enrichment_enabled = {enrichment}
source_scope_default = "{source_scope_default}"
framework_allowlist = {_render_framework_allowlist(framework_allowlist)}
"""


def _render_local_example() -> str:
    return """# Optional local overrides for machine-specific secrets and endpoints.
# Keep this file as reference; use .forge/config.local.toml for actual local values.
# Do not commit secrets.

[llm]
provider = "openai_compatible"

[llm.openai_compatible]
base_url = "http://localhost:8080/v1"
model = "local/dev-model"
api_key_env = "FORGE_OPENAI_API_KEY"
"""


def _collect_existing(repo_root: Path) -> list[str]:
    existing: list[str] = []
    forge_root = repo_root / ".forge"
    for rel in (*MANAGED_REPO_FILES, *MANAGED_LOCAL_FILES):
        if (forge_root / rel).exists():
            existing.append(rel)
    return existing


def _print_plan(repo_root: Path, files: dict[str, str], existing: set[str]) -> None:
    print("=== FORGE INIT ===")
    print(f"Target root: {repo_root}")
    print("\n--- Planned Files ---")
    for rel in files:
        action = "update" if rel in existing else "create"
        scope = "repo-owned" if rel in MANAGED_REPO_FILES else "local-example"
        print(f"- {action}: .forge/{rel} ({scope})")
    print("\n--- Git Guidance ---")
    print("Commit: .forge/config.toml, .forge/review-rules.toml, .forge/template-meta.toml")
    print("Do not commit secrets; keep real local overrides in .forge/config.local.toml")


def run(request: CommandRequest, args, session: ExecutionSession) -> int:
    repo_root = Path(args.repo_root).resolve()
    is_json = args.output_format == "json"
    session.record_effect(EffectClass.READ_ONLY, f"inspect init target {repo_root}")
    if not repo_root.exists() or not repo_root.is_dir():
        summary = f"Init target is not a valid directory: {repo_root}"
        contract = build_contract(
            capability=request.capability.value,
            profile=request.profile.value,
            summary=summary,
            evidence=[],
            uncertainty=["invalid init target path"],
            next_step="Provide a valid directory via --repo-root and rerun forge init.",
            sections={"status": "invalid_target"},
        )
        if args.output_format == "json":
            emit_contract_json(contract)
        else:
            print(summary)
        return 1

    if args.list_templates:
        payload = {
            "status": "templates_listed",
            "templates": [
                {"id": t.template_id, "description": t.description}
                for t in INIT_TEMPLATES.values()
            ]
        }
        summary = "Available init templates listed."
        contract = build_contract(
            capability=request.capability.value,
            profile=request.profile.value,
            summary=summary,
            evidence=[],
            uncertainty=[],
            next_step="Run: forge init --template <template-id> --non-interactive",
            sections=payload,
        )
        if args.output_format == "json":
            emit_contract_json(contract)
        else:
            print("=== FORGE INIT TEMPLATES ===")
            for item in payload["templates"]:
                print(f"- {item['id']}: {item['description']}")
        return 0

    interactive = not bool(args.non_interactive)
    if interactive and not sys.stdin.isatty():
        summary = "Interactive init requires a TTY."
        contract = build_contract(
            capability=request.capability.value,
            profile=request.profile.value,
            summary=summary,
            evidence=[],
            uncertainty=["stdin is not interactive"],
            next_step="Use --non-interactive with --template to initialize without prompts.",
            sections={"status": "non_tty"},
        )
        if args.output_format == "json":
            emit_contract_json(contract)
        else:
            print(summary)
        return 1

    selected_template = args.template or "balanced"
    if interactive and not args.template:
        print("Select Forge init template:")
        for item in INIT_TEMPLATES.values():
            print(f"- {item.template_id}: {item.description}")
        selected_template = _prompt_choice("Template", list(INIT_TEMPLATE_CHOICES), "balanced")
    if selected_template not in INIT_TEMPLATES:
        summary = f"Unknown template: {selected_template}"
        contract = build_contract(
            capability=request.capability.value,
            profile=request.profile.value,
            summary=summary,
            evidence=[],
            uncertainty=["template id not found"],
            next_step="Run: forge init --list-templates",
            sections={"status": "invalid_template"},
        )
        if args.output_format == "json":
            emit_contract_json(contract)
        else:
            print(summary)
        return 1
    template = INIT_TEMPLATES[selected_template]

    output_language = args.output_language or template.output_language
    review_strictness = args.review_strictness or template.review_strictness
    index_enrichment_enabled = template.index_enrichment_enabled
    source_scope_default = str(getattr(args, "source_scope", "") or INIT_SOURCE_SCOPE_DEFAULT)
    framework_allowlist = _parse_framework_allowlist(getattr(args, "framework_allowlist", None))
    if args.index_enrichment is not None:
        index_enrichment_enabled = args.index_enrichment == "enabled"

    if interactive:
        output_language = _prompt_choice("Output language", list(INIT_OUTPUT_LANGUAGE_CHOICES), output_language)
        review_strictness = _prompt_choice(
            "Review strictness", list(INIT_REVIEW_STRICTNESS_CHOICES), review_strictness
        )
        index_enrichment_enabled = _prompt_yes_no(
            "Enable index explain-summary enrichment?",
            default=index_enrichment_enabled,
        )
        source_scope_default = _prompt_choice(
            "Default source scope",
            list(INIT_SOURCE_SCOPE_CHOICES),
            source_scope_default,
        )
        print("Framework allowlist (optional, comma-separated IDs like typo3@12). Leave empty for none.")
        framework_allowlist = _parse_framework_allowlist(input("> ").strip())

    files_to_write = {
        "config.toml": _render_config(
            template=template,
            output_language=output_language,
            index_enrichment_enabled=index_enrichment_enabled,
            source_scope_default=source_scope_default,
            framework_allowlist=framework_allowlist,
        ),
        "review-rules.toml": _render_review_rules(review_strictness=review_strictness),
        "template-meta.toml": _render_template_meta(
            template_id=template.template_id,
            interactive=interactive,
            review_strictness=review_strictness,
            output_language=output_language,
            index_enrichment_enabled=index_enrichment_enabled,
            source_scope_default=source_scope_default,
            framework_allowlist=framework_allowlist,
        ),
        "config.local.toml.example": _render_local_example(),
    }

    existing = set(_collect_existing(repo_root))
    if not is_json:
        _print_plan(repo_root, files_to_write, existing)

    if existing and not args.force:
        if args.non_interactive:
            summary = "Init would overwrite existing .forge init files; explicit force is required."
            contract = build_contract(
                capability=request.capability.value,
                profile=request.profile.value,
                summary=summary,
                evidence=[],
                uncertainty=["existing init-managed files found"],
                next_step="Re-run with --force to allow overwrite.",
                sections={"status": "overwrite_blocked", "existing_files": sorted(existing)},
            )
            if args.output_format == "json":
                emit_contract_json(contract)
            else:
                print(f"\nBlocked: {summary}")
            return 1
        allowed = _prompt_yes_no(
            "Existing init files were found. Overwrite managed files?",
            default=False,
        )
        if not allowed:
            summary = "Init cancelled; existing files were kept unchanged."
            contract = build_contract(
                capability=request.capability.value,
                profile=request.profile.value,
                summary=summary,
                evidence=[],
                uncertainty=["user canceled overwrite"],
                next_step="Re-run forge init with --force or choose a different target.",
                sections={"status": "canceled"},
            )
            if args.output_format == "json":
                emit_contract_json(contract)
            else:
                print(f"\n{summary}")
            return 1

    if args.dry_run:
        summary = "Init dry-run completed; no files were written."
        contract = build_contract(
            capability=request.capability.value,
            profile=request.profile.value,
            summary=summary,
            evidence=[],
            uncertainty=[],
            next_step="Run forge init again without --dry-run to write files.",
            sections={
                "status": "dry_run",
                "template_id": template.template_id,
                "source_scope_default": source_scope_default,
                "framework_allowlist": framework_allowlist,
                "planned_files": [f".forge/{rel}" for rel in files_to_write],
            },
        )
        if args.output_format == "json":
            emit_contract_json(contract)
        else:
            print("\nDry-run complete. No files written.")
        return 0

    if interactive:
        proceed = _prompt_yes_no("Write files now?", default=True)
        if not proceed:
            summary = "Init cancelled before writing files."
            contract = build_contract(
                capability=request.capability.value,
                profile=request.profile.value,
                summary=summary,
                evidence=[],
                uncertainty=["user canceled write"],
                next_step="Re-run forge init when ready.",
                sections={"status": "canceled"},
            )
            if args.output_format == "json":
                emit_contract_json(contract)
            else:
                print(f"\n{summary}")
            return 1

    written: list[str] = []
    for rel, content in files_to_write.items():
        write_forge_file(repo_root, rel, content, session)
        written.append(f".forge/{rel}")

    summary = f"Forge init completed using template '{template.template_id}'."
    sections = {
        "status": "initialized",
        "template_id": template.template_id,
        "written_files": written,
        "repo_owned_files": [f".forge/{rel}" for rel in MANAGED_REPO_FILES],
        "local_example_files": [f".forge/{rel}" for rel in MANAGED_LOCAL_FILES],
        "settings": {
            "output_language": output_language,
            "review_strictness": review_strictness,
            "index_enrichment_enabled": index_enrichment_enabled,
            "source_scope_default": source_scope_default,
            "framework_allowlist": framework_allowlist,
        },
    }
    contract = build_contract(
        capability=request.capability.value,
        profile=request.profile.value,
        summary=summary,
        evidence=[],
        uncertainty=[],
        next_step="Commit repo-owned .forge files and review generated defaults.",
        sections=sections,
    )
    if args.output_format == "json":
        emit_contract_json(contract)
    else:
        print("\n--- Result ---")
        print(summary)
        print("Written files:")
        for rel in written:
            print(f"- {rel}")
    return 0
